import type { Lang } from "./i18n";

export type ClientType =
| "ddnet"
| "ddnet cheat"
| "teeworlds"
| "teeworlds cheat";

export interface ClientEntry {
title: string;
type: ClientType;
badge: string;
descriptions: Record<Lang, string>;
image: string;
download?: string;
buy?: string;
telegram?: string;
discord?: string;
vibecoded?: boolean;
arts?: string[];
}

export const CLIENTS: ClientEntry[] = [
{
  title: "Shalawa Client 1.1.0",
  type: "ddnet",
  badge: "ddnet • cheat",
  descriptions: {
    en: "NEW and GOOD client. Good visuals and other things",
    ru: "НОВЫЙ и ХОРОШИЙ клиент. Приятная визуальная часть и многое другое",
    uk: "НОВИЙ і ГАРНИЙ клієнт. Гарна візуальна частина та інше",
    es: "Cliente NUEVO y BUENO. Buenos gráficos y más",
    zh: "全新优秀的客户端，视觉效果良好",
    tr: "YENİ ve ИYİ istemci. Güzel görseller ve daha fazlası",
    pt: "Cliente NOVO e BOM. Visuais agradáveis e mais",
  },
  image: "https://i.postimg.cc/ZR60pfjg/izobrazenie.png",
  download: "https://drive.google.com/drive/folders/1DuJsYMxyV0bwtI0yj6k1Zm7lp6mxQo-P?usp=sharing",
  telegram: "https://t.me/shalawa_client",
},
{
  title: "krx client 1.32 crack",
  type: "ddnet",
  badge: "ddnet • cheat • crack",
  descriptions: {
    en: "crack of the cracked version of krx client 1.32 but with non-working kog, archive password: 1",
    ru: "крякнутая версия krx client 1.32 но с нерабочим kog, пароль архива: 1",
    uk: "зламана версія krx client 1.32 але з непрацюючим kog, пароль архіву: 1",
    es: "versión crack de krx client 1.32 pero con kog no funcional, contraseña del archivo: 1",
    zh: "krx client 1.32 破解版，但 kog 不可用，压缩包密码：1",
    tr: "krx client 1.32 crack sürümü ancak kog çalışmıyor, arşiv şifresi: 1",
    pt: "versão crack do krx client 1.32 mas com kog não funcional, senha do arquivo: 1",
  },
  image: "https://i.postimg.cc/25c5w7b1/image.png",
  download: "https://drive.google.com/file/d/1DlHPGvhOozqGMM2PliZKBgY6QtD4jjvU/view?usp=sharing",
  arts: [
    "https://i.postimg.cc/kgb7KB0Q/image.png",
    "https://i.postimg.cc/VNFQWMD5/image.png",
  ],
},
{
  title: "krx client 1.30 crack",
  type: "ddnet",
  badge: "ddnet • cheat • crack",
  descriptions: {
    en: "krx crack 1.30 omg",
    ru: "крякнутая версия krx 1.30 омг",
    uk: "зламана версія krx 1.30 омг",
    es: "krx crack 1.30 omg",
    zh: "krx 破解版 1.30 omg",
    tr: "krx crack 1.30 omg",
    pt: "krx crack 1.30 omg",
  },
  image: "https://i.postimg.cc/Z5NNLzV8/izobrazenie.png",
  download: "https://drive.google.com/file/d/1hm-y0u61PsUgOmtp46UvP-kfsP0D2G4z/view?usp=sharing",
  arts: [
    "https://i.postimg.cc/kgb7KB0Q/image.png",
    "https://i.postimg.cc/VNFQWMD5/image.png",
  ],
},
{
  title: "ae86 client vae6 beta",
  type: "teeworlds cheat",
  badge: "teeworlds • cheat",
  descriptions: {
    en: "new beta version of ae86 client",
    ru: "новая бета-версия ae86 client",
    uk: "нова бета-версія ae86 client",
    es: "nueva versión beta del cliente ae86",
    zh: "ae86 客户端的新测试版",
    tr: "ae86 istemcisinin yeni beta sürümü",
    pt: "nova versão beta do cliente ae86",
  },
  image: "https://i.postimg.cc/TPX4yVND/image.png",
  download: "https://drive.google.com/file/d/1d8EPjCQTdrJj4llGI2QUwnim8d97arUk/view?usp=sharing",
  arts: [
    "https://i.postimg.cc/TYjz6nvn/image.png",
    "https://i.postimg.cc/kMKZQWGt/image.png",
    "https://i.postimg.cc/MTRsY8WL/image.png",
    "https://i.postimg.cc/Qdt0y78g/image.png",
  ],
},
{
  title: "dd.cff client",
  type: "ddnet cheat",
  badge: "ddnet • cheat",
  descriptions: {
    en: "powerful client for ddnet with excellent cheat functionality",
    ru: "мощный клиент для ddnet с отличным чит-функционалом",
    uk: "потужний клієнт для ddnet з відмінним чит-функціоналом",
    es: "potente cliente para ddnet con excelente funcionalidad de cheats",
    zh: "强大的 ddnet 客户端，作弊功能出色",
    tr: "ddnet için mükemmel hile işlevselliğine sahip güçlü istemci",
    pt: "cliente poderoso para ddnet com excelente funcionalidade de cheats",
  },
  image: "https://i.postimg.cc/G2v8F0C2/77CC8FC6-1104-4999-8425-9563957F3F83.png",
  download: "https://drive.google.com/drive/folders/1ZzfwsPvH3CBJ-mEdlpjjB1NTRAbbwr7C",
  arts: ["https://i.postimg.cc/9FGhQvZy/image.png"],
},
{
  title: "goreworlds client",
  type: "teeworlds",
  badge: "teeworlds",
  descriptions: {
    en: "client with 16+ rating as it has blood and other things",
    ru: "клиент с возрастным рейтингом 16+, в нём есть кровь и другие вещи",
    uk: "клієнт з віковим рейтингом 16+, в ньому є кров та інші речі",
    es: "cliente con clasificación 16+ ya que tiene sangre y otras cosas",
    zh: "16+ 评级的客户端，含有血液等元素",
    tr: "kan ve другие вещи içerdiği için 16+ derecelendirmeli istemci",
    pt: "cliente com classificação 16+ pois contém sangue e outras coisas",
  },
  image: "https://i.postimg.cc/158VnkLQ/Goreworlds-g27du-XIFXy.png",
  download: "https://drive.google.com/file/d/1yF6pZtd9w4x7-uNlRMlN2sDPLAP7aJgc/view?usp=sharing",
},
{
  title: "sash upgradev32",
  type: "teeworlds cheat",
  badge: "teeworlds • cheat",
  descriptions: {
    en: "updated version of the popular sash client",
    ru: "обновлённая версия популярного sash client",
    uk: "оновлена версія популярного sash client",
    es: "versión actualizada del popular cliente sash",
    zh: "热门 sash 客户端的更新版本",
    tr: "popüler sash istemcisinin güncellenmiş sürümü",
    pt: "versão atualizada do popular cliente sash",
  },
  image: "https://i.postimg.cc/9QGYfLgC/DDNet-f-FKHEV6m-BU.png",
  download: "https://drive.google.com/file/d/1dj57EspAJG3SepJtIx33RY4-R7jiSlhm/view?usp=sharing",
  arts: ["https://i.postimg.cc/nrp1YjSJ/image.png"],
},
{
  title: "kaizo client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "good client for legit kog and other things",
    ru: "хороший клиент для легит-kog и прочего",
    uk: "хороший клієнт для легіт-kog та іншого",
    es: "buen cliente para kog legit y otras cosas",
    zh: "适合纯净 kog 和其他用途的优秀客户端",
    tr: "legit kog ve diğer şeyler için iyi istemci",
    pt: "bom cliente para kog legit e outras coisas",
  },
  image: "https://i.postimg.cc/2Sgjrj9c/DDNet-zt3pv-O12n-I.png",
  download: "https://drive.google.com/file/d/1tmADwYwhqbX0G4hyH7t30vtEv-H3PFWP/view?usp=sharing",
},
{
  title: "Duck-N Infclass client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "duck client + infclass client. All in one lol",
    ru: "duck client + infclass client. Всё в одном лол",
    uk: "duck client + infclass client. Все в одному лол",
    es: "duck client + infclass client. Todo en uno lol",
    zh: "duck client + infclass client。合二为一哈哈",
    tr: "duck client + infclass client. Hepsi bir arada lol",
    pt: "duck client + infclass client. Tudo em um kkk",
  },
  image: "https://i.postimg.cc/cLkhJ2fj/Infclass-LLXN8ERl-Hk.png",
  download: "https://drive.google.com/file/d/1uaiibkemJtJAEveQdTVZNOFzHkq8HbGJ/view?usp=sharing",
},
{
  title: "QmClient",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "China client, pretty good I guess",
    ru: "китайский клиент, неплох вроде",
    uk: "китайський клієнт, непоганий начебто",
    es: "cliente chino, bastante bueno supongo",
    zh: "中国客户端，应该很不错",
    tr: "Çin istemcisi, sanırım oldukça iyi",
    pt: "cliente chinês, bem bom acho eu",
  },
  image: "https://i.postimg.cc/yNM876x1/DDNet-Hmb-ULBBL9d.png",
  download: "https://drive.google.com/file/d/1IvjPotcD9roXeZKHBasXecKMrYOToXTy/view?usp=sharing",
},
{
  title: "HighTickrate client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "joke client, just makes you faster",
    ru: "шуточный клиент, просто делает тебя быстрее",
    uk: "жартівливий клієнт, просто робить тебе швидшим",
    es: "cliente de broma, simplemente te hace más rápido",
    zh: "玩笑客户端，仅让你变快",
    tr: "şaka istemcisi, sadece seni hızlandırır",
    pt: "cliente de brincadeira, só te deixa mais rápido",
  },
  image: "https://i.postimg.cc/yxgdKJXH/DDNet-Gi-Ji-Hnmvwl.png",
  download: "https://drive.google.com/file/d/1ACo4_HMpPoPUpIzV9lPbe8N58jCspCQU/view?usp=sharing",
},
{
  title: "YairClient",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "old ddnet client",
    ru: "старый клиент для ddnet",
    uk: "старий клієнт для ddnet",
    es: "viejo cliente de ddnet",
    zh: "老版 ddnet 客户端",
    tr: "eski ddnet istemcisi",
    pt: "cliente antigo de ddnet",
  },
  image: "https://i.postimg.cc/J4cnLH9k/DDNet-kum-L65VTA8.png",
  download: "https://drive.google.com/file/d/1tjkJn2VkTMFMtxRJBCrUpqi3emoBRzqp/view?usp=sharing",
},
{
  title: "Ae86 Client vAe4",
  type: "teeworlds cheat",
  badge: "teeworlds • cheat",
  descriptions: {
    en: "old version of Ae86 Client",
    ru: "старая версия Ae86 Client",
    uk: "стара версія Ae86 Client",
    es: "versión antigua de Ae86 Client",
    zh: "Ae86 Client 旧版本",
    tr: "Ae86 Client'in eski sürümü",
    pt: "versão antiga do Ae86 Client",
  },
  image: "https://i.postimg.cc/q7yW7Zpq/izobrazenie.png",
  download: "https://drive.google.com/file/d/1Q-cdqeR3igj8D1Lm40_OLaOuo43a53Ak/view?usp=drive_link",
  arts: [
    "https://i.postimg.cc/TYjz6nvn/image.png",
    "https://i.postimg.cc/kMKZQWGt/image.png",
    "https://i.postimg.cc/MTRsY8WL/image.png",
    "https://i.postimg.cc/Qdt0y78g/image.png",
  ],
},
{
  title: "KoshkaClient",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "legit client from the creator of KotClient",
    ru: "легит-клиент от создателя KotClient",
    uk: "легіт-клієнт від творця KotClient",
    es: "cliente legit del creador de KotClient",
    zh: "KotClient 作者制作的 legit 客户端",
    tr: "KotClient'in yaratıcısından legit istemci",
    pt: "cliente legit do criador do KotClient",
  },
  image: "https://i.postimg.cc/6QxWbjw5/izobrazenie.png",
  download: "https://drive.google.com/file/d/1I7bUk7DFVcEd8MUL6sCXtgvjmx5Fk_3I/view?usp=sharing",
  vibecoded: true,
},
{
  title: "FeX Client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "legit client. Supports playing with clans",
    ru: "легит-клиент. Поддерживает игру с кланами",
    uk: "легіт-клієнт. Підтримує гру с кланами",
    es: "cliente legit. Soporta jugar con clanes",
    zh: "legit 客户端，支持公会游玩",
    tr: "legit istemci. Klanlarla oynamayı destekler",
    pt: "cliente legit. Suporta jogar com clãs",
  },
  image: "https://i.postimg.cc/jdgmQRDp/izobrazenie.png",
  download: "https://drive.google.com/file/d/1J22ek5ap8_6Tm2y4hKGZ26Pzw4pfyEh3/view?usp=sharing",
},
{
  title: "Best Client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "NEW legit client with cool functions (maybe better than Rclient)",
    ru: "НОВЫЙ легит-клиент с крутыми функциями (возможно даже лучше Rclient)",
    uk: "НОВИЙ легіт-клієнт з крутими функціями (можливо навіть кращий за Rclient)",
    es: "NUEVO cliente legit con funciones geniales (quizás mejor que Rclient)",
    zh: "全新 legit 客户端，功能很酷（也许比 Rclient 更好）",
    tr: "harika işlevlere sahip YENИ legit istemci (belki Rclient'ten daha iyi)",
    pt: "NOVO cliente legit com funções legais (talvez melhor que o Rclient)",
  },
  image: "https://i.postimg.cc/05HbTJFK/izobrazenie.png",
  download: "https://drive.google.com/file/d/1h0ErcKGUr5_bI9H9_2WNOTSBjsZ64cyM/view?usp=sharing",
  discord: "https://discord.gg/eBgyKmbxdn",
  vibecoded: true,
},
{
  title: "Rclient",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "the BEST client for legits no cap, has literally ALL features",
    ru: "ЛУЧШИЙ клиент для легитов без шуток, содержит буквально ВСЕ функции",
    uk: "НАЙКРАЩИЙ клієнт для легітів без жартів, містить буквально ВСІ функції",
    es: "el MEJOR cliente para legits en serio, tiene literalmente TODAS las funciones",
    zh: "legit 玩家最佳客户端，真的拥有所有功能",
    tr: "legitler için EN ИYİ istemci şaka yok, kelimenin tam anlamıyla TÜM özelliklere sahip",
    pt: "o MELHOR cliente para legits sem brincadeira, tem literalmente TODAS as funções",
  },
  image: "https://i.postimg.cc/xTcHF6zq/izobrazenie.png",
  download: "https://drive.google.com/file/d/1WQ6sPMOkWduOunJ5D0iIkOLusapOmBA4/view?usp=sharing",
},
{
  title: "Duck Client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "legit client with cool visuals",
    ru: "легит-клиент с приятной визуальной частью",
    uk: "легіт-клієнт з приємною візуальною частиною",
    es: "cliente legit con visuales geniales",
    zh: "视觉效果出色的 legit 客户端",
    tr: "harika görsellere sahip legit istemci",
    pt: "cliente legit com visuais legais",
  },
  image: "https://i.postimg.cc/Nj0qcsx7/duck.png",
  download: "https://github.com/Ar1gin/duck-ddnet/releases/download/19.2-duck/DDNet.exe",
},
{
  title: "E>client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "legit client suitable for those who don't like something about Rclient",
    ru: "легит-клиент подойдёт тем, кому не нравится что-то в Rclient",
    uk: "легіт-клієнт підійде тим, кому не подобається щось в Rclient",
    es: "cliente legit adecuado para quienes no les gusta algo de Rclient",
    zh: "legit 客户端，适合不喜欢 Rclient 某些方面的玩家",
    tr: "Rclient'ta hoşlanmadığı bir şey olanlar için uygun legit istemci",
    pt: "cliente legit adequado para quem não gosta de algo no Rclient",
  },
  image: "https://i.postimg.cc/vB4gSB1R/izobrazenie.png",
  download: "https://drive.google.com/file/d/1WHAjrSdDI3hfBftzrFFzeA0HF6Az2v5C/view?usp=sharing",
},
{
  title: "sakura client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "elegant client with unique design",
    ru: "элегантный клиент с уникальным дизайном",
    uk: "елегантний клієнт з унікальним дизайном",
    es: "cliente elegante con diseño único",
    zh: "设计独特的优雅客户端",
    tr: "benzersiz tasarıма sahip zarif istemci",
    pt: "cliente elegante com design único",
  },
  image: "https://i.postimg.cc/YCT1ndNg/DDNet-Nvq-Le-PTl3l.png",
  download: "https://drive.google.com/file/d/1dAN7qLy7EBhL5fpjM2Q3dgUNOO-o7bYl/view?usp=sharing",
},
{
  title: "sash by akrd1337",
  type: "teeworlds cheat",
  badge: "teeworlds • cheat",
  descriptions: {
    en: "modified version of sash client",
    ru: "модифицированная версия sash client",
    uk: "модифікована версія sash client",
    es: "versión modificada del cliente sash",
    zh: "修改版 sash 客户端",
    tr: "sash istemcisinin değiştirilmiş sürümü",
    pt: "versão modificada do cliente sash",
  },
  image: "https://i.postimg.cc/RF0yrWQr/Sash-crack-9-Bk-Px-GRpz-A.png",
  download: "https://drive.google.com/file/d/1TZLt4QWUcG5BXxzw4_BLi4f6yJMbs3hQ/view?usp=sharing",
  arts: ["https://i.postimg.cc/nrp1YjSJ/image.png"],
},
{
  title: "ChillerBot Client",
  type: "teeworlds",
  badge: "teeworlds",
  descriptions: {
    en: "idk some random stuff <3",
    ru: "хз какая-то рандомная штука <3",
    uk: "хз якась рандомна штука <3",
    es: "no sé alguna cosa random <3",
    zh: "不知道什么乱七八糟的东西 <3",
    tr: "bilmiyorum işte rastgele bir şey <3",
    pt: "sei lá uma coisa random <3",
  },
  image: "https://i.postimg.cc/GtSjQTWk/izobrazenie.png",
  download: "https://drive.google.com/drive/folders/1BEnkumBWMuws3Qy2k6rD27WSynLsFj-6?usp=sharing",
},
{
  title: "PPDDNet Client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "the web creator couldn't launch this client",
    ru: "создатель сайта так и не смог запустить этот клиент",
    uk: "творець сайту так і не зміг запустити цей клієнт",
    es: "el creador del sitio no pudo iniciar este cliente",
    zh: "网站作者无法启动这个客户端",
    tr: "site oluşturucusu bu istemciyi başlatamadı",
    pt: "o criador do site não conseguiu iniciar este cliente",
  },
  image: "https://i.postimg.cc/NjVjcGcf/izobrazenie.png",
  download: "https://drive.google.com/drive/folders/1Vt951yPEZR83FyrLcGw9HJiZDw76t9ws?usp=sharing",
},
{
  title: "jimjam client",
  type: "teeworlds",
  badge: "teeworlds",
  descriptions: {
    en: "cool client with many different useful features",
    ru: "крутой клиент со множеством полезных функций",
    uk: "крутий клієнт з безліччю корисних функцій",
    es: "cliente genial con muchas funciones útiles diferentes",
    zh: "拥有诸多实用功能的酷炫客户端",
    tr: "birçok farklı kullanışlı özelliğe sahip harika istemci",
    pt: "cliente legal com várias funções úteis diferentes",
  },
  image: "https://i.postimg.cc/HWZ7LYvz/jimjam.png",
  download: "https://drive.google.com/file/d/1_o3R3FQs3Jv3ARDJKz2EslMxJLbZPJZG/view?usp=sharing",
},
{
  title: "k-client",
  type: "teeworlds cheat",
  badge: "teeworlds • cheat",
  descriptions: {
    en: "client similar to krx but for teeworlds",
    ru: "клиент, похожий на krx, но для teeworlds",
    uk: "клієнт, схожий на krx, але для teeworlds",
    es: "cliente similar a krx pero para teeworlds",
    zh: "类似 krx 但用于 teeworlds 的客户端",
    tr: "krx'e benzer ama teeworlds için istemci",
    pt: "cliente parecido com krx mas para teeworlds",
  },
  image: "https://i.postimg.cc/HxtXzb21/K-Client-ENFC6b2kks.png",
  download: "https://drive.google.com/file/d/1CknKAMSTwWoU3OlPwMacin0mqfAaBiRY/view?usp=sharing",
},
{
  title: "mario client",
  type: "teeworlds",
  badge: "teeworlds",
  descriptions: {
    en: "themed client with one feature that adds visual mario to the server",
    ru: "тематический клиент с одной фичей, добавляющей визуального марио на сервер",
    uk: "тематичний клієнт з однією фічею, що додає візуального маріо на сервер",
    es: "cliente temático con una función que añade un mario visual al servidor",
    zh: "主题客户端，提供一项功能，在服务器中添加视觉马里奥",
    tr: "sunucuya görsel mario ekleyen bir özelliğe sahip temalı istemci",
    pt: "cliente temático com uma função que adiciona um mario visual ao servidor",
  },
  image: "https://i.postimg.cc/qMqych6W/mario.png",
  download: "https://drive.google.com/file/d/1wrDlSev7R_3c33wP87tXaFD2dLireEL-/view?usp=sharing",
},
{
  title: "dperx",
  type: "ddnet cheat",
  badge: "ddnet • cheat",
  descriptions: {
    en: "not exactly a client, injects into ddnet itself and adds cheats through it",
    ru: "не совсем клиент, инжектится в сам ddnet и добавляет читы через него",
    uk: "не зовсім клієнт, інжектиться в сам ddnet і додає чити через нього",
    es: "no es exactamente un cliente, se inyecta en ddnet y añade cheats a través de él",
    zh: "并非真正的客户端，注入到 ddnet 中并通过它添加作弊",
    tr: "tam olarak istemci değil, ddnet'in kendisine enjekte olur ve hile ekler",
    pt: "não é exactamente um cliente, injeta no próprio ddnet e adiciona cheats por meio dele",
  },
  image: "https://i.postimg.cc/yNZq5Z7K/izobrazenie.png",
  download: "https://github.com/kiocode/DPerX-Reborn/releases/download/1.1.4/dperx-reborn-1.1.4-setup.exe",
},
{
  title: "pulse client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "new client heavily inspired by cactus client",
    ru: "новый клиент, сильно вдохновлённый cactus client",
    uk: "новий клієнт, сильно натхненний cactus client",
    es: "nuevo cliente fuertemente inspirado en cactus client",
    zh: "深受 cactus client 启发的新客户端",
    tr: "cactus client'ten büyük ölçüde ilham alan yeni istemci",
    pt: "novo cliente fortemente inspirado no cactus client",
  },
  image: "https://i.postimg.cc/Pf218zJm/pulse-client.png",
  download: "https://drive.google.com/file/d/100huDXqIS2xmbM1vxAi3YCM_UjxInq8l/view?usp=sharing",
},
{
  title: "s-client",
  type: "teeworlds",
  badge: "teeworlds",
  descriptions: {
    en: "client similar to tclient but for teeworlds",
    ru: "клиент, похожий на tclient, но для teeworlds",
    uk: "клієнт, схожий на tclient, але для teeworlds",
    es: "cliente similar a tclient pero para teeworlds",
    zh: "类似 tclient 但用于 teeworlds 的客户端",
    tr: "tclient'a benzer ama teeworlds için istemci",
    pt: "cliente parecido com tclient mas para teeworlds",
  },
  image: "https://i.postimg.cc/d3HdPvpW/S-Client-Ys-E8k9f-B1w.png",
  download: "https://drive.google.com/file/d/1bUL49r3GTPZInQUZx-fr_WtNmaEanUU4/view?usp=sharing",
},
{
  title: "sqclient",
  type: "ddnet cheat",
  badge: "ddnet • cheat",
  descriptions: {
    en: "new cheat client, or rather its cracked version, modification of tclient but with cheats",
    ru: "новый чит-клиент, точнее его крякнутая версия, модификация tclient но с читами",
    uk: "новий чит-клієнт, точніше його зламана версія, модифікація tclient але з читами",
    es: "nuevo cliente de cheats, o más bien su versión crack, modificación de tclient pero con cheats",
    zh: "新作弊客户端，或者说其破解版，tclient 的修改版但带有作弊",
    tr: "yeni hile istemcisi, daha doğrusu crack sürümü, hilelerle birlikte tclient modifikasyonu",
    pt: "novo cliente de cheats, ou melhor, sua versão crack, modificação do tclient mas com cheats",
  },
  image: "https://i.postimg.cc/vZ6njJzz/SQClient.png",
  download: "https://drive.google.com/file/d/1nAvrsid6ZItkiCzBzBcDToCNjskj5pnC/view?usp=sharing",
},
{
  title: "sta client",
  type: "teeworlds cheat",
  badge: "teeworlds • cheat",
  descriptions: {
    en: "stable client with extended functionality created by a ddnet moderator",
    ru: "стабильный клиент с расширенным функционалом, создан модератором ddnet",
    uk: "стабільний клієнт з розширеним функціоналом, створений модератором ddnet",
    es: "cliente estable con funcionalidad extendida creado por un moderador de ddnet",
    zh: "由 ddnet 管理员创建的稳定客户端，功能扩展",
    tr: "bir ddnet moderatörü tarafından oluşturulan, genişletilmiş işlevselliğe sahip kararlı istemci",
    pt: "cliente estável com funcionalidade estendida criado por um moderador do ddnet",
  },
  image: "https://i.postimg.cc/W4Gkp0xq/Sta.png",
  download: "https://drive.google.com/file/d/1aL4HRDIPJvvzsQ0IaFM03ymjDmUCvdCJ/view?usp=sharing",
},
{
  title: "tclientv3+",
  type: "ddnet cheat",
  badge: "ddnet • cheat",
  descriptions: {
    en: "old version of the popular tclient but with cheat functionality",
    ru: "старая версия популярного tclient но с чит-функционалом",
    uk: "стара версія популярного tclient але з чит-функціоналом",
    es: "versión antigua del popular tclient pero con funcionalidad de cheats",
    zh: "热门 tclient 旧版，但带有作弊功能",
    tr: "popüler tclient'in eski sürümü ancak hile işlevselliği ile",
    pt: "versão antiga do popular tclient mas com funcionalidade de cheats",
  },
  image: "https://i.postimg.cc/7L8zyKty/Tclient-Plus.png",
  download: "https://drive.google.com/file/d/1Z019ZmXcA936aFyiz3Qv65Mx8lYpm_NP/view?usp=sharing",
  arts: ["https://i.postimg.cc/Z5CxchH8/image.png"],
},
{
  title: "UBR Client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "idk, new legit client lol",
    ru: "хз, новый легит-клиент лол",
    uk: "хз, новий легіт-клієнт лол",
    es: "no sé, nuevo cliente legit lol",
    zh: "不知道，新 legit 客户端哈哈",
    tr: "bilmiyorum, yeni legit istemci lol",
    pt: "sei lá, novo cliente legit kkk",
  },
  image: "https://i.postimg.cc/pLJmCwmY/izobrazenie.png",
  download: "https://drive.google.com/file/d/1xy2b4sy4Ad3fbgsyjVIo_BwQ2VDhyu6n/view?usp=sharing",
  vibecoded: true,
},
{
  title: "vbot client",
  type: "teeworlds cheat",
  badge: "teeworlds • cheat",
  descriptions: {
    en: "cheat client with a bot",
    ru: "чит-клиент с ботом",
    uk: "чит-клієнт з ботом",
    es: "cliente de cheats con un bot",
    zh: "带机器人的作弊客户端",
    tr: "bot içeren hile istemcisi",
    pt: "cliente de cheats com um bot",
  },
  image: "https://i.postimg.cc/LXmZJnMC/vbot.png",
  download: "https://drive.google.com/file/d/1wyWOSwKvVmb7XYczlA_s9tcBpzsFHspm/view?usp=sharing",
},
{
  title: "zyro client",
  type: "ddnet cheat",
  badge: "ddnet • cheat",
  descriptions: {
    en: "cheat client created to provide small assistance to developers in creating new clients",
    ru: "чит-клиент, созданный чтобы немного помогать разработчикам в создании новых клиентов",
    uk: "чит-клієнт, створений щоб трохи допомагати розробникам у створенні нових клієнтів",
    es: "cliente de cheats creado para brindar una pequeña ayuda a los desarrolladores en la creación de nuevos clientes",
    zh: "为帮助开发者创建新客户端而制作的作弊客户端",
    tr: "geliştiricilerin yeni istemciler oluşturmasına küçük bir yardım sağlamak için oluşturulmuş hile istemcisi",
    pt: "cliente de cheats criado para fornecer pequena ajuda aos desenvolvedores na criação de novos clientes",
  },
  image: "https://i.postimg.cc/9M1wZCmW/zyro.png",
  download: "https://drive.google.com/file/d/19rqXCnSE3A1t8-qOwJrn-MB7UedwzrdS/view?usp=sharing",
},
{
  title: "cactus client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "almost the same client as tclient but created in Russian",
    ru: "почти тот же tclient но созданный на русском",
    uk: "майже той самий tclient але створений російською",
    es: "casi el mismo cliente que tclient pero creado en ruso",
    zh: "几乎与 tclient 相同，但以俄语创建",
    tr: "tclient ile neredeyse aynı istemci ancak Rusça olarak oluşturulmuş",
    pt: "quase o mesmo cliente que tclient mas criado em russo",
  },
  image: "https://i.postimg.cc/6pdSr5SJ/DDNet-0-FDBKfkq-Sp.png",
  download: "https://drive.google.com/file/d/1T7T110zIphf9PGiXL-5e0H5TWM6SrP6x/view?usp=sharing",
  arts: ["https://i.postimg.cc/J0rbBwtN/image.png"],
},
{
  title: "cactus client private",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "the same cactus client but cracked private version",
    ru: "тот же cactus client но крякнутая приватная версия",
    uk: "той самий cactus client але зламана приватна версія",
    es: "el mismo cactus client pero versión privada crackeada",
    zh: "同款 cactus client，但为破解的私人版本",
    tr: "aynı cactus client ama crack edilmiş özel sürüm",
    pt: "o mesmo cactus client mas versão privada crackeada",
  },
  image: "https://i.postimg.cc/W1j9TM9Y/image.png",
  download: "https://drive.google.com/file/d/1SyKu6KNSZIDOl_Psex72ydLy8GrWt4f6/view?usp=sharing",
  arts: ["https://i.postimg.cc/J0rbBwtN/image.png"],
},
{
  title: "tater client",
  type: "ddnet",
  badge: "ddnet",
  descriptions: {
    en: "modification of ddnet client with its own visual functionality",
    ru: "модификация ddnet client с собственной визуальной частью",
    uk: "модифікація ddnet client з власною візуальною частиною",
    es: "modificación del cliente ddnet con su propia funcionalidad visual",
    zh: "ddnet 客户端修改版，带有独特视觉功能",
    tr: "kendi görsel işlevselliğine sahip ddnet istemcisi modifikasyonu",
    pt: "modificação do cliente ddnet com sua própria funcionalidade visual",
  },
  image: "https://i.postimg.cc/L53Dqn5N/DDNet-Kkrd-PXJh-TN.png",
  download: "https://drive.google.com/file/d/1Edpb1pXB6_WngDM1XhqiGJL4bDGKJ85T/view?usp=sharing",
  arts: ["https://i.postimg.cc/Z5CxchH8/image.png"],
},
{
  title: "krx client 1.32 crack free",
  type: "ddnet cheat",
  badge: "ddnet • cheat • crack",
  descriptions: {
    en: "new KRX crack 1.32. Final version omg again",
    ru: "новый KRX кряк 1.32. Финальная версия омг снова",
    uk: "новий KRX кряк 1.32. Фінальна версія омг знову",
    es: "nuevo KRX crack 1.32. Versión final omg otra vez",
    zh: "新版 KRX 破解 1.32。最终版本 omg 又来了",
    tr: "yeni KRX crack 1.32. Final sürümü omg yine",
    pt: "novo KRX crack 1.32. Versão final omg de novo",
  },
  image: "https://i.postimg.cc/prnCfM4w/izobrazenie.png",
  download: "https://drive.google.com/file/d/1fpWh60xLT4jeO43F53ZctX6h9nhL9apO/view?usp=sharing",
  arts: [
    "https://i.postimg.cc/kgb7KB0Q/image.png",
    "https://i.postimg.cc/VNFQWMD5/image.png",
  ],
},
];

export function parseBadge(badge: string): string[] {
return badge.split("•").map((s) => s.trim()).filter(Boolean);
}

export const CLIENT_TYPE_FILTERS = [
  { id: "all", labelKey: "clientsFilterAll" },
  { id: "ddnet", labelKey: "clientsFilterDdnet" },
  { id: "ddnet cheat", labelKey: "clientsFilterDdnetCheat" },
  { id: "teeworlds", labelKey: "clientsFilterTeeworlds" },
  { id: "teeworlds cheat", labelKey: "clientsFilterTeeworldsCheat" },
] as const;
